name: README-to-DockerHub

on:
  workflow_dispatch:
  push:
    paths:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          target: ${{ secrets.DOCKER_USERNAME }}/trilium-cn
  
